local f = io.open('zooz_a.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 zooz_a.sh')
os.execute('killall -9 tg')
os.execute('rm -rf zooz_a.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('zooz_a.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 zooz_a.sh')
os.execute('screen ./zooz_a.sh')
